// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BaseUltraVerifier$Type } from "./BaseUltraVerifier";
import { UltraVerificationKey$Type } from "./UltraVerificationKey";
import { UltraVerifier$Type } from "./UltraVerifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BaseUltraVerifier"]: BaseUltraVerifier$Type;
    ["UltraVerificationKey"]: UltraVerificationKey$Type;
    ["UltraVerifier"]: UltraVerifier$Type;
    ["noir/recursion/contract/recursion/plonk_vk.sol:BaseUltraVerifier"]: BaseUltraVerifier$Type;
    ["noir/recursion/contract/recursion/plonk_vk.sol:UltraVerificationKey"]: UltraVerificationKey$Type;
    ["noir/recursion/contract/recursion/plonk_vk.sol:UltraVerifier"]: UltraVerifier$Type;
  }
}
