// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BaseUltraVerifier$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BaseUltraVerifier",
  "sourceName": "noir/recursion/contract/recursion/plonk_vk.sol",
  "abi": [
    {
      "inputs": [],
      "name": "EC_SCALAR_MUL_FAILURE",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "MOD_EXP_FAILURE",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "PROOF_FAILURE",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "expected",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "actual",
          "type": "uint256"
        }
      ],
      "name": "PUBLIC_INPUT_COUNT_INVALID",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "PUBLIC_INPUT_GE_P",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "PUBLIC_INPUT_INVALID_BN128_G1_POINT",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "getVerificationKeyHash",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "_proof",
          "type": "bytes"
        },
        {
          "internalType": "bytes32[]",
          "name": "_publicInputs",
          "type": "bytes32[]"
        }
      ],
      "name": "verify",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BaseUltraVerifier",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BaseUltraVerifier$Type["abi"]>>;
  export function deployContract(
    contractName: "noir/recursion/contract/recursion/plonk_vk.sol:BaseUltraVerifier",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BaseUltraVerifier$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BaseUltraVerifier",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BaseUltraVerifier$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "noir/recursion/contract/recursion/plonk_vk.sol:BaseUltraVerifier",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BaseUltraVerifier$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BaseUltraVerifier",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BaseUltraVerifier$Type["abi"]>>;
  export function getContractAt(
    contractName: "noir/recursion/contract/recursion/plonk_vk.sol:BaseUltraVerifier",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BaseUltraVerifier$Type["abi"]>>;
}
